# Package Manager
source ~/.config/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle nvm
antigen bundle rvm
antigen bundle rails
antigen bundle fzf
antigen bundle ripgrep
antigen bundle httpie
antigen bundle git-auto-fetch
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async
# antigen bundle sindresorhus/pure
antigen bundle wting/autojump
antigen bundle zdharma/zsh-diff-so-fancy
antigen bundle paulirish/git-open
antigen apply


# Path to your oh-my-zsh installation.
export ZSH=/Users/$USER/.oh-my-zsh
export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH="/usr/local/opt/gettext/bin:$PATH"
export PATH="/Applications/calibre.app/Contents/MacOS:$PATH"
# export VISUAL=nvim
# export EDITOR="$VISUAL"
# export NVM_AUTO_USE=true
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Add makana to PATH if it exists
if [ -d ~/Code/salesforce/makana-platform/ ]; then
    source $HOME/Code/salesforce/makana-platform/bin/makana > /dev/null 2>&1
fi

HYPHEN_INSENSITIVE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white'


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""

DEFAULT_USER=$USER

# # Set Vi Keybindings
bindkey -v
bindkey "^?" backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[OM" accept-line
autoload -Uz surround
autoload -U select-quoted
zle -N select-quoted
for m in visual viopp; do
  for c in {a,i}{\',\",\`}; do
    bindkey -M $m $c select-quoted
  done
done
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey '^r' history-incremental-search-backward
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
bindkey -M viins "^[OA"  up-line-or-search
bindkey -M viins "^[OB"  down-line-or-search
bindkey "^ " autosuggest-accept
export KEYTIMEOUT=25

if [[ -f ~/.aliases ]]; then
    source ~/.aliases
fi

if [[ -f ~/.functions ]]; then
    source ~/.functions
fi

if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

# Add docker autocompletion to bash
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# Add autojump support
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

export GPG_TTY=$(tty)
export KEYFILE=~/.ssh/id_rsa
export PATH="/usr/local/opt/node@14/bin:$PATH"
export PATH="$(yarn global bin):$PATH"

autoload -U promptinit; promptinit
prompt pure
