source ~/.proxy_url
# Turns Proxy on
proxy() {
    export HTTP_PROXY=$PROXY_URL
    export HTTPS_PROXY=$PROXY_URL
    export HTTP_PROXY=$PROXY_URL
    export HTTPS_PROXY=$PROXY_URL
    export NO_PROXY=.ge.com,localhost,127.0.0.1,204.130.41.105*
	npm config set PROXY $PROXY_URL
	npm config set HTTPS-PROXY $PROXY_URL
}

# Turns Proxy off
noproxy() {
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset NO_PROXY
}

NO_PROXY="github.build.ge.com, localhost, 127.0.0.1, api.grc-apps.svc.ice.ge.com,login.grc-apps.svc.ice.ge.com,loggregator.grc-apps.svc.ice.ge.com,uaa.grc-apps.svc.ice.ge.com,console.grc-apps.svc.ice.ge.com,grc-apps.svc.ice.ge.com"

# Ping google.com. If command fails it's because we're behind the proxy, so set the GE network proxy
noproxy
wget -q --spider https://google.com
if [[ $? != 0 ]]; then
    echo "On GE network. Setting proxy"
    proxy
fi


# Package Manager
source ~/.config/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle nvm
antigen bundle rvm
antigen bundle rails
antigen bundle fzf
antigen bundle ripgrep
antigen bundle httpie
antigen bundle git-auto-fetch
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle rupa/z
antigen bundle zdharma/zsh-diff-so-fancy
antigen bundle paulirish/git-open
antigen apply


# Path to your oh-my-zsh installation.
export ZSH=/Users/$USER/.oh-my-zsh
export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export VISUAL=nvim
export EDITOR="$VISUAL"
export NVM_AUTO_USE=true
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
HYPHEN_INSENSITIVE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white'


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""

DEFAULT_USER=$USER

# # Set Vi Keybindings
bindkey -v
bindkey "^?" backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[OM" accept-line
autoload -Uz surround
autoload -U select-quoted
zle -N select-quoted
for m in visual viopp; do
  for c in {a,i}{\',\",\`}; do
    bindkey -M $m $c select-quoted
  done
done
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
bindkey -M viins "^[OA"  up-line-or-search
bindkey -M viins "^[OB"  down-line-or-search
bindkey "^ " autosuggest-accept
export KEYTIMEOUT=25

if [[ -f ~/.dotfiles/zsh/aliases ]]; then
    source ~/.dotfiles/zsh/aliases
	echo "Adding aliases"
fi

pfind(){
    lsof -t -i :$1
}

unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}
j() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}


# Install (one or multiple) selected application(s)
# using "brew search" as source input
# mnemonic [B]rew [I]nstall [P]lugin
bip() {
  local inst=$(brew search | fzf -m)

  if [[ $inst ]]; then
    for prog in $(echo $inst);
    do; brew install $prog; done;
  fi
}

# Update (one or multiple) selected application(s)
# mnemonic [B]rew [U]pdate [P]lugin
bup() {
  local upd=$(brew leaves | fzf -m)

  if [[ $upd ]]; then
    for prog in $(echo $upd);
    do; brew upgrade $prog; done;
  fi
}

# Delete (one or multiple) selected application(s)
# mnemonic [B]rew [C]lean [P]lugin (e.g. uninstall)
bcp() {
  local uninst=$(brew leaves | fzf -m)

  if [[ $uninst ]]; then
    for prog in $(echo $uninst);
    do; brew uninstall $prog; done;
  fi
}

# Install (one or multiple) selected application(s)
# using "brew search" as source input
# mnemonic [C]ask [I]nstall [P]lugin
cip() {
  local inst=$(brew search --casks | fzf -m)

  if [[ $inst ]]; then
    for prog in $(echo $inst);
    do; brew cask install $prog; done;
  fi
}

# Delete (one or multiple) selected application(s)
# mnemonic [C]ask [C]lean [P]lugin (e.g. uninstall)
ccp() {
  local uninst=$(brew cask list | fzf -m)

  if [[ $uninst ]]; then
    for prog in $(echo $uninst);
    do; brew cask uninstall $prog; done;
  fi
}

if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
